#!/bin/bash
SERVICES="rpc nfsd ntpd nginx sshd avahidaemon samba"

# run & log functions
. /etc/rc.d/rc.runlog

queue(){
  atq | grep -Pom1 '^\d+'
}

JOB=$(queue)
if [[ -n $JOB ]]; then
  atrm $JOB 2>/dev/null
  log "execute queued job $JOB"
else
  exit 0
fi

for cmd in $SERVICES; do
  if [[ $cmd == avahidaemon && $1 == force ]]; then
    /etc/rc.d/rc.$cmd update force &>/dev/null
  else
    /etc/rc.d/rc.$cmd update &>/dev/null
  fi
done
exit 0
