#!/bin/bash
SERVICES="rpc nfsd ntpd nginx sshd avahidaemon samba"

# run & log functions
. /etc/rc.d/rc.runlog

queue(){
  atq | grep -Pom1 '^\d+'
}

if [[ ! -r /usr/local/emhttp/state/var.ini ]]; then
    # sanity check - exit if no var.ini file, implies emhttpd is not running yet
    log "/usr/local/emhttp/state/var.ini does not exist, aborting."
    exit 1
fi

JOB=$(queue)
if [[ -n $JOB ]]; then
  atrm $JOB 2>/dev/null
  log "execute queued job $JOB"
else
  exit 0
fi

for cmd in $SERVICES; do
  /etc/rc.d/rc.$cmd update &>/dev/null
done
exit 0
