#!/usr/bin/php -q
<?php
// usage: ftpusers user_config_data
// user_config_data = pipe (|) delimited root folders for user in the format of user=/path/to/root/folder

$user_config_dir = "/boot/config/vsftpd.user_config_dir";

$user_options = explode("|", $argv[1]);

foreach(explode("|", $argv[1]) as $user_config)
{
  $user_config_parts = explode("=", trim($user_config));
  $user_config_file = $user_config_dir . "/" . $user_config_parts[0];
  $user_config_root_folder = $user_config_parts[1];

  // if no root folder and this user has an existing config file
  if($user_config_root_folder === "" && file_exists($user_config_file) && is_file($user_config_file))
  {
    // delete the config file
    unlink($user_config_file);
  }
  else if($user_config_root_folder !== "" && file_exists($user_config_root_folder) && is_dir($user_config_root_folder))
  {
    file_put_contents($user_config_file, "local_root=" . $user_config_root_folder . "\n");
  }
}

?>
