#!/bin/bash
set -u

plugin="/usr/local/emhttp/plugins/dynamix.plugin.manager/scripts/plugin"
history_file="${1:-}"

[ -x "$plugin" ] || exit 1
[ -n "$history_file" ] || exit 1

if [ -n "${2:-}" ]; then
  exec "$plugin" history-delete "$history_file" nchan
fi
exec "$plugin" history-delete "$history_file"
